name: Size Check

on:
  pull_request:
    branches:
      - '**'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1 # Disable cleanup for homebrew, we don't need it on CI

jobs:
  upload--build:
    name: Upload Build to Emerge
    runs-on: macos-13
    steps:
      - name: Install Bot SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.BOT_SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/ruby-cache
      - name: Run match_me
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPSTORE_API_KEY: ${{ secrets.APPSTORE_API_KEY }}
        run: bundle exec fastlane match_me
      - name: Run emerge_upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_NUM: ${{ github.event.number }}
          GITHUB_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          GITHUB_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          EMERGE_API_TOKEN: ${{ secrets.EMERGE_API_TOKEN }}
        run: bundle exec fastlane emerge_upload
