name: Full Checks

on:
  schedule:
    - cron: '0 1 * * *' # run at 1AM UTC
  workflow_dispatch:

env:
  HOMEBREW_NO_INSTALL_CLEANUP=1: 1 # Disable cleanup for homebrew, we don't need it on CI

jobs:
  build-and-test-release:
    name: Test LLC (Release)
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/set-build-image-var
    - name: Cache RubyGems
      uses: actions/cache@v2
      id: rubygem-cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ env.ImageVersion }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-${{ env.ImageVersion }}-gem-
    - name: Cache Mint
      uses: actions/cache@v2
      id: mint-cache
      with:
        path: /usr/local/lib/mint
        key: ${{ runner.os }}-mint-${{ hashFiles('./Mintfile') }}
        restore-keys: ${{ runner.os }}-mint-
    - uses: ./.github/actions/bootstrap
    - name: Run LLC Tests (Release)
      run: bundle exec fastlane test_release
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: "You shall not pass!"
        job_name: "Test LLC (Release)"
        fields: message,commit,author,action,eventName,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      if: ${{ github.event_name == 'push' && failure() }}

  build-and-test-ui-release:
    name: Test UI (Release)
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/set-build-image-var
    - name: Cache RubyGems
      uses: actions/cache@v2
      id: rubygem-cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ env.ImageVersion }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-${{ env.ImageVersion }}-gem-
    - name: Cache Mint
      uses: actions/cache@v2
      id: mint-cache
      with:
        path: /usr/local/lib/mint
        key: ${{ runner.os }}-mint-${{ hashFiles('./Mintfile') }}
        restore-keys: ${{ runner.os }}-mint-
    - uses: ./.github/actions/bootstrap
    - name: Run UI Tests (Release)
      run: bundle exec fastlane test_ui_release device:"iPhone 12"
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: "You shall not pass!"
        job_name: "Test UI (Release)"
        fields: message,commit,author,action,eventName,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      if: ${{ github.event_name == 'push' && failure() }}

  stress-tests:
    name: Stress Test LLC - Latest iOS (Release)
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/set-build-image-var
    - name: Cache RubyGems
      uses: actions/cache@v2
      id: rubygem-cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ env.ImageVersion }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-${{ env.ImageVersion }}-gem-
    - name: Cache Mint
      uses: actions/cache@v2
      id: mint-cache
      with:
        path: /usr/local/lib/mint
        key: ${{ runner.os }}-mint-${{ hashFiles('./Mintfile') }}
        restore-keys: ${{ runner.os }}-mint-
    - uses: ./.github/actions/bootstrap
    - name: Run Stress Tests - Latest iOS (Release)
      run: bundle exec fastlane stress_test_release device:"iPhone 12"

  stress-tests-ios13:
    name: Stress Test LLC - iOS 13.5 (Release)
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/set-build-image-var
    - name: Cache RubyGems
      uses: actions/cache@v2
      id: rubygem-cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ env.ImageVersion }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-${{ env.ImageVersion }}-gem-
    - name: Cache Mint
      uses: actions/cache@v2
      id: mint-cache
      with:
        path: /usr/local/lib/mint
        key: ${{ runner.os }}-mint-${{ hashFiles('./Mintfile') }}
        restore-keys: ${{ runner.os }}-mint-
    - uses: ./.github/actions/bootstrap
    - uses: ./.github/actions/prepare-ios-simulator
      with:
        device: "iPhone 11"
        ios: "13.5"
        xcode: "11.5"
    - name: Run Stress Tests - iOS 13.5 (Release)
      run: bundle exec fastlane stress_test_release device:"iPhone 11 (13.5)"

  stress-tests-ios12:
    name: Stress Test LLC - iOS 12.4 (Release)
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/set-build-image-var
    - name: Cache RubyGems
      uses: actions/cache@v2
      id: rubygem-cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ env.ImageVersion }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-${{ env.ImageVersion }}-gem-
    - name: Cache Mint
      uses: actions/cache@v2
      id: mint-cache
      with:
        path: /usr/local/lib/mint
        key: ${{ runner.os }}-mint-${{ hashFiles('./Mintfile') }}
        restore-keys: ${{ runner.os }}-mint-
    - uses: ./.github/actions/bootstrap
    - uses: ./.github/actions/prepare-ios-simulator
      with:
        device: "iPhone 11"
        ios: "12.4"
        xcode: "10.3"
    - name: Run Stress Tests
      run: bundle exec fastlane stress_test_release device:"iPhone 11 (12.4)"

  build-apps-ios13:
    name: Build Sample App - iOS 13.5
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/set-build-image-var
    - name: Cache RubyGems
      uses: actions/cache@v2
      id: rubygem-cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ env.ImageVersion }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-${{ env.ImageVersion }}-gem-
    - name: Cache Mint
      uses: actions/cache@v2
      id: mint-cache
      with:
        path: /usr/local/lib/mint
        key: ${{ runner.os }}-mint-${{ hashFiles('./Mintfile') }}
        restore-keys: ${{ runner.os }}-mint-
    - uses: ./.github/actions/bootstrap
    - uses: ./.github/actions/prepare-ios-simulator
      with:
        device: "iPhone 11"
        ios: "13.5"
        xcode: "11.5"
    - name: Build Sample App - iOS 13.5
      run: bundle exec fastlane build_sample device:"iPhone 11 (13.5)"
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: "You shall not pass!"
        job_name: "Build Sample App - iOS 13.5"
        fields: message,commit,author,action,eventName,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      if: ${{ github.event_name == 'push' && failure() }}

  build-apps-ios12:
    name: Build Sample App - iOS 12.4
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/set-build-image-var
    - name: Cache RubyGems
      uses: actions/cache@v2
      id: rubygem-cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ env.ImageVersion }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-${{ env.ImageVersion }}-gem-
    - name: Cache Mint
      uses: actions/cache@v2
      id: mint-cache
      with:
        path: /usr/local/lib/mint
        key: ${{ runner.os }}-mint-${{ hashFiles('./Mintfile') }}
        restore-keys: ${{ runner.os }}-mint-
    - uses: ./.github/actions/bootstrap
    - uses: ./.github/actions/prepare-ios-simulator
      with:
        device: "iPhone 7"
        ios: "12.4"
        xcode: "10.3"
    - name: Build Sample App - iOS 12.4
      run: bundle exec fastlane build_sample device:"iPhone 7 (12.4)"
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: "You shall not pass!"
        job_name: "Build Sample App - iOS 12.4"
        fields: message,commit,author,action,eventName,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      if: ${{ github.event_name == 'push' && failure() }}
