name: SDK Size

on:
  pull_request:

  workflow_dispatch:

  push:
    branches:
      - develop

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1 # Disable cleanup for homebrew, we don't need it on CI

jobs:
  sdk_size:
    name: Metrics
    runs-on: macos-15
    env:
      GITHUB_TOKEN: '${{ secrets.CI_BOT_GITHUB_TOKEN }}'
      GITHUB_PR_NUM: ${{ github.event.pull_request.number }}
    steps:
      - name: Connect Bot
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.BOT_SSH_PRIVATE_KEY }}

      - uses: actions/checkout@v3.1.0

      - uses: ./.github/actions/bootstrap

      - name: Run General SDK Size Metrics
        run: bundle exec fastlane show_frameworks_sizes
        timeout-minutes: 30
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPSTORE_API_KEY: ${{ secrets.APPSTORE_API_KEY }}

      - name: Run Detailed SDK Size Metrics
        run: bundle exec fastlane size_analyze
        timeout-minutes: 30
